name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        target: [test, test++, valgrind]
        ssl: [MBEDTLS, OPENSSL]
    name: linux ${{ matrix.target }} CC=${{ matrix.cc }} SSL=${{ matrix.ssl }}
    env:
      IPV6: 0
      CC: ${{ matrix.cc }}
      SSL: ${{ matrix.ssl }}
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get update ; sudo apt-get install libmbedtls-dev valgrind
    - name: test
      run: make ${{ matrix.target }}
    - name: unamalgamated
      run: make unamalgamated
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install libmbedtls-dev
    - name: examples
      run: make clean examples
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install jq mbedtls openssl
    - name: make
      run: make test++ upload-coverage IPV6=0 ASAN_OPTIONS=
    - name: openssl
      run: make test SSL=OPENSSL IPV6=0 ASAN_OPTIONS= OPENSSL=`echo /usr/local/Cellar/openssl*/*`
    - name: exports
      run: make mg_prefix
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: vc98
      run: make vc98
    - name: vc2017
      run: make vc2017
    - name: mingw
      run: make mingw
    - name: mingw++
      run: make mingw++
  arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: arm
      run: make arm
  ti:
    runs-on: mdashnet/ccs
    steps:
    - uses: actions/checkout@v3
    - name: ti
      run: make -C examples/ti/ti-ek-tm4c1294xl-http-server  